image: python:latest

before_script:
   - pip install twine
   - python setup.py sdist

deploy_staging:
  stage: deploy
  variables:
    TWINE_USERNAME: "__token__"
    TWINE_PASSWORD: "$PIPI_TOKEN"
  script:
    - twine upload --repository-url $PYPRI_REPOSITORY_URL dist/*
  except:
    - tags

deploy_production:
  stage: deploy
  variables:
    TWINE_USERNAME: "__token__"
    TWINE_PASSWORD: "$PIPI_TOKEN"
  script:
    - twine upload dist/*
  only:
    - tags

#    username: "__token__"
#    password: "$PIPI_TOKEN"

