image: python:latest

stages:
  - deploy

before_script:
  - python -VVV
  - pip install -r requirements.txt
  - python3 setup.py sdist bdist_wheel

deploy:
  stage: deploy
  variables:
    provider: pypi
    username: "__token__"
    password: "$PIPI_TOKEN"
    skip_existing: true

