language: python
python:
  - "3.8"

install:
  - python3 -m pip install -r requirements.txt

script:
  - cd "${TRAVIS_BUILD_DIR}/"
  - python3 setup.py sdist bdist_wheel

deploy:
  provider: pypi
  username: "__token__"
  password: "$PIPI_TOKEN"
  #kip_existing: true
