language: python
python:
  - "3.8"

install:
  - python3 -m pip install -r requirements.txt
  #- python3 -m pip install --user --upgrade setuptools wheel

script:
  - cp .pypirc ~/.pypirc
  - cd "${TRAVIS_BUILD_DIR}/"
  - python3 setup.py sdist bdist_wheel
  - python3 -m twine upload --repository mypdns dist/*

